/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    inquiries: Inquiry;
    cocktails: Cocktail;
    testimonials: Testimonial;
    categories: Category;
    clients: Client;
    events: Event;
    packages: Package;
    pages: Page;
    footers: Footer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      drinks: 'cocktails';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    cocktails: CocktailsSelect<false> | CocktailsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  status?: ('new' | 'contacted' | 'proposal_sent' | 'booked' | 'lost') | null;
  selectedPackage?: (number | null) | Package;
  /**
   * Final negotiated price (PHP)
   */
  agreedPrice?: number | null;
  /**
   * Internal notes for this client (e.g., agreed price, specific needs).
   */
  adminNotes?: string | null;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  email?: string | null;
  mobileViber: string;
  preferredContact?: ('Viber' | 'Facebook Messenger' | 'Email') | null;
  /**
   * Username without the m.me/ prefix
   */
  messengerUsername?: string | null;
  eventDate: string;
  eventType?: string | null;
  venue: string;
  guestCount: number;
  specialRequests?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  basePrice: number;
  /**
   * List the liquors, mixers, and hours included.
   */
  inclusions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktails".
 */
export interface Cocktail {
  id: number;
  name: string;
  image: number | Media;
  category: number | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * e.g., Signature Cocktails, Classic Cocktails, Shooters
   */
  name: string;
  /**
   * Toggle this on to show this category and its drinks as a slider on the homepage.
   */
  featuredOnLanding?: boolean | null;
  /**
   * Lower numbers appear first on the page (e.g., 1, 2, 3).
   */
  order?: number | null;
  drinks?: {
    docs?: (number | Cocktail)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The actual review or testimonial text.
   */
  quote: string;
  clientName: string;
  /**
   * e.g., Marketing Lead, AboitizLand
   */
  clientRole?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientType?: ('individual' | 'corporate' | 'coordinator') | null;
  /**
   * e.g., Aboitiz, San Miguel, etc.
   */
  companyName?: string | null;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  email?: string | null;
  mobileViber: string;
  totalSpent?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  eventName: string;
  client: number | Client;
  paymentStatus?: ('deposit_pending' | 'deposit_paid' | 'fully_paid') | null;
  eventDate: string;
  setupTime?: string | null;
  venue: string;
  packageBooked?: (number | null) | Package;
  /**
   * Final price if negotiated differently from the base package price.
   */
  agreedPrice?: number | null;
  operationsNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            heading: string;
            /**
             * This text will appear in the primary brand color next to the main heading.
             */
            headingHighlight?: string | null;
            description?: string | null;
            backgroundImage: number | Media;
            primaryButtonText?: string | null;
            primaryButtonLink?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * The small uppercase label above the heading
             */
            eyebrow: string;
            heading: string;
            /**
             * Second line before the highlighted word
             */
            headingContinued?: string | null;
            headingHighlight?: string | null;
            stats?:
              | {
                  /**
                   * e.g., 50+, 100%
                   */
                  value: string;
                  /**
                   * e.g., Events Served
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * First image is the large featured square. 4 more will fill the 2x2 grid
             */
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * The small uppsercase label above the heading
             */
            eyebrow: string;
            heading: string;
            backgroundImage: number | Media;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cocktailTasting';
          }
        | {
            /**
             * The small uppercase label above the heading
             */
            eyebrow: string;
            headingLine1: string;
            headingLine2?: string | null;
            /**
             * Select the testimonials to display. Leave empty to show all.
             */
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            heading: string;
            /**
             * Upload brand/partner logos. They will be split in two rows and auto-scrolled
             */
            logos: {
              image: number | Media;
              /**
               * Accessible label for the logo.
               */
              alt?: string | null;
              height?: ('h-5' | 'h-6' | 'h-8' | 'h-10' | 'h-12') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'brands';
          }
        | {
            categories?: (number | Category)[] | null;
            cardsPerView?: ('3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'menu';
          }
        | {
            heading: string;
            headingScript: string;
            backgroundImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            /**
             * Each entry is a milestone on the timeline.
             */
            entries?:
              | {
                  /**
                   * e.g. Jan 2022
                   */
                  dateLabel: string;
                  description: string;
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Controls the site-wide footer content. Only one footer record is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  /**
   * short tagline shown next to the small martini logo.
   */
  tagline: string;
  /**
   * Navigation links shown under the "Explore" column
   */
  exploreLinks?:
    | {
        label: string;
        /**
         * e.g. /about or https://example.com
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Links shown under the "Socials" column
   */
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Name shown in "© Name, Year".
   */
  copyrightName?: string | null;
  locationText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'cocktails';
        value: number | Cocktail;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  selectedPackage?: T;
  agreedPrice?: T;
  adminNotes?: T;
  firstName?: T;
  lastName?: T;
  fullName?: T;
  email?: T;
  mobileViber?: T;
  preferredContact?: T;
  messengerUsername?: T;
  eventDate?: T;
  eventType?: T;
  venue?: T;
  guestCount?: T;
  specialRequests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktails_select".
 */
export interface CocktailsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  clientName?: T;
  clientRole?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  featuredOnLanding?: T;
  order?: T;
  drinks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientType?: T;
  companyName?: T;
  firstName?: T;
  lastName?: T;
  fullName?: T;
  email?: T;
  mobileViber?: T;
  totalSpent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  eventName?: T;
  client?: T;
  paymentStatus?: T;
  eventDate?: T;
  setupTime?: T;
  venue?: T;
  packageBooked?: T;
  agreedPrice?: T;
  operationsNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  basePrice?: T;
  inclusions?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              headingHighlight?: T;
              description?: T;
              backgroundImage?: T;
              primaryButtonText?: T;
              primaryButtonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              headingContinued?: T;
              headingHighlight?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cocktailTasting?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              backgroundImage?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              eyebrow?: T;
              headingLine1?: T;
              headingLine2?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        brands?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    height?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        menu?:
          | T
          | {
              categories?: T;
              cardsPerView?: T;
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              heading?: T;
              headingScript?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              entries?:
                | T
                | {
                    dateLabel?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  tagline?: T;
  exploreLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightName?: T;
  locationText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}